import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import WrapperProvider from '@/lib/wrapper-provider';
import { Navbar } from '@/app/__components__/navbar';

const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body suppressHydrationWarning className={inter.className}>
				<WrapperProvider>
					<Navbar />
					{children}
				</WrapperProvider>
			</body>
		</html>
	);
}
